export const items = [

  /* =======================
     🌍 100 JUGADORES HISTÓRICOS (MUNDIAL)
  ======================= */
  "Lionel Messi",
  "Cristiano Ronaldo",
  "Pelé",
  "Diego Maradona",
  "Johan Cruyff",
  "Zinedine Zidane",
  "Ronaldinho",
  "Ronaldo Nazário",
  "Neymar",
  "Kylian Mbappé",
  "Erling Haaland",
  "Robert Lewandowski",
  "Luis Suárez",
  "Karim Benzema",
  "Andrés Iniesta",
  "Xavi Hernández",
  "Luka Modrić",
  "Toni Kroos",
  "Kevin De Bruyne",
  "Mohamed Salah",
  "Harry Kane",
  "Wayne Rooney",
  "David Beckham",
  "Thierry Henry",
  "Steven Gerrard",
  "Iker Casillas",
  "Gianluigi Buffon",
  "Manuel Neuer",
  "Virgil van Dijk",
  "Sergio Ramos",
  "Cafu",
  "Roberto Carlos",
  "Philipp Lahm",
  "Carlos Tevez",
  "Ángel Di María",
  "Antoine Griezmann",
  "Jude Bellingham",
  "Vinícius Jr",
  "Zlatan Ibrahimović",
  "Didier Drogba",
  "Andrea Pirlo",
  "Francesco Totti",
  "Arjen Robben",
  "Franck Ribéry",
  "Thomas Müller",
  "Miroslav Klose",
  "Bastian Schweinsteiger",
  "David Villa",
  "Fernando Torres",
  "Mesut Özil",
  "Marco Reus",
  "Xabi Alonso",
"Romário",
  "Kaká",
  "Hugo Sánchez",
  "Luis Figo",
  "Raúl González",
  "Carles Puyol",
  "Gerard Piqué",
  "Marcelo",
  "Dani Alves",
  "Thibaut Courtois",
  "Roberto Baggio",
  "Eusébio",
  "Bobby Charlton",
  "Zico",
    "Messi",
  /* =======================
     🇲🇽 50 JUGADORES HISTÓRICOS LIGA MX
  ======================= */
  "Cuauhtémoc Blanco",
  "Hugo Sánchez",
  "Rafael Márquez",
  "Javier Hernández",
  "Jared Borgetti",
  "Luis García",
  "Oswaldo Sánchez",
  "Guillermo Ochoa",
  "Miguel Calero",
  "José Saturnino Cardozo",
  "Antonio Mohamed",
  "Christian Giménez",
  "Lucas Lobos",
  "Darío Verón",
  "Jonathan dos Santos",
  "Oribe Peralta",
  "Carlos Vela",
  "Héctor Herrera",
  "Andrés Guardado",
  "Héctor Moreno",
  "Paul Aguilar",
  "Jesús Corona",
  "Luis Roberto Alves Zague",
  "Matías Vuoso",
  "Carlos Salcido",
  "Ricardo Osorio",
  "Adolfo Bautista",
  "Rodolfo Pizarro",
  "Damián Álvarez",
  "Ángel Reyna",
  "Jorge Campos",
"Humberto Suazo",

  /* =======================
     🏟️ 50 CLUBES HISTÓRICOS
  ======================= */
  "Real Madrid",
  "FC Barcelona",
  "Manchester United",
  "Manchester City",
  "Liverpool",
  "Chelsea",
  "Arsenal",
  "Bayern Múnich",
  "Borussia Dortmund",
  "Juventus",
  "AC Milan",
  "Inter de Milán",
  "Napoli",
  "Roma",
  "PSG",
  "Olympique de Marsella",
  "Ajax",
  "PSV Eindhoven",
  "Feyenoord",
  "Porto",
  "Benfica",
  "Sporting Lisboa",
  "Atlético de Madrid",
  "Sevilla",
  "Valencia",
  "Real Sociedad",
  "Athletic Club",
  "Tottenham",
  "West Ham",
  "Leicester City",
  "Celtic",
  "Rangers",
  "Galatasaray",
  "Fenerbahçe",
  "Boca Juniors",
  "River Plate",
  "Flamengo",
  "Palmeiras",
  "Santos",
  "Corinthians",
  "São Paulo",
  "Club América",
  "Chivas",
  "Cruz Azul",
  "Pumas UNAM",
  "Tigres UANL",
  "Monterrey",
  "Toluca",
  "León"
];
